export const env = {
  chainId: Number(import.meta.env.VITE_CHAIN_ID ?? 4663),
  rpcUrl: import.meta.env.VITE_RPC_URL ?? 'https://rpc.mainnet.chain.robinhood.com',
  usdg: import.meta.env.VITE_USDG as `0x${string}`,
  stratToken: import.meta.env.VITE_STRAT_TOKEN as `0x${string}`,
  strategyHook: import.meta.env.VITE_STRATEGY_HOOK as `0x${string}`,
  v4SwapExecutor: import.meta.env.VITE_V4_SWAP_EXECUTOR as `0x${string}`,
  lotReader: (import.meta.env.VITE_LOT_READER || '') as `0x${string}` | '',
  buybackManager: import.meta.env.VITE_BUYBACK_MANAGER as `0x${string}`,
  feeCollector: import.meta.env.VITE_FEE_COLLECTOR as `0x${string}`,
  treasury: import.meta.env.VITE_TREASURY as `0x${string}`,
  dividendsManifestUrl: (import.meta.env.VITE_DIVIDENDS_MANIFEST_URL || '') as string,
  stateView: import.meta.env.VITE_STATE_VIEW as `0x${string}`,
  stratUsdgPoolId: import.meta.env.VITE_STRAT_USDG_POOL_ID as `0x${string}`,
  nvdaUsdgPoolId: import.meta.env.VITE_NVDA_USDG_POOL_ID as `0x${string}`,
  nvda: import.meta.env.VITE_NVDA as `0x${string}`,
  lotManager: import.meta.env.VITE_LOT_MANAGER as `0x${string}`,
  lpPositionManager: import.meta.env.VITE_LP_POSITION_MANAGER as `0x${string}`,
  assetExecutor: (import.meta.env.VITE_ASSET_EXECUTOR || '') as `0x${string}` | '',
  launchManager: (import.meta.env.VITE_LAUNCH_MANAGER || '') as `0x${string}` | '',
  tokenSymbol: (import.meta.env.VITE_TOKEN_SYMBOL as string) || 'NVDASTR',
  usdgDecimals: Number(import.meta.env.VITE_USDG_DECIMALS ?? 6),
  stratDecimals: 18,
  nvdaDecimals: Number(import.meta.env.VITE_NVDA_DECIMALS ?? 18),
  poolFee: 3000,
  tickSpacing: 60,
} as const;
